# Generated by Django 2.1.2 on 2018-11-07 14:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=core.models.get_user_file_path),
        ),
    ]
