# Generated by Django 2.1.2 on 2018-11-25 20:19

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('core', '0002_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('created_at', models.DateTimeField()),
                ('users', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=core.models.get_user_file_path)),
                ('bio', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
        ),
    ]
