# Generated by Django 2.1.2 on 2018-10-15 23:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 23, 45, 11, 455117, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
