# Generated by Django 2.1.2 on 2018-10-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cookTime',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='prepTime',
        ),
    ]
