# Generated by Django 2.1.2 on 2018-10-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0003_auto_20181023_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='trending_count',
            field=models.IntegerField(default=0),
        ),
    ]
