# Generated by Django 2.1.2 on 2018-10-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0008_auto_20181023_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipecategory',
            name='recipe',
        ),
        migrations.AddField(
            model_name='category',
            name='assignable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(to='RecipeApp.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='RecipeCategory',
        ),
    ]
