# Generated by Django 2.1.2 on 2018-10-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0009_auto_20181023_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cookTime',
            new_name='cook_time',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='prepTime',
            new_name='prep_time',
        ),
    ]
